In [1]:
import pandas as pd
import numpy as np

In [19]:
ds1 = pd.read_csv('/home/user/Desktop/Lending Club/Short Datasets/accepted_2007_to_2018Q4-3.csv')

/tmp/ipykernel_512122/2051011383.py:1: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139) have mixed types. Specify dtype option on import or set low_memory=False.
  ds1 = pd.read_csv('/home/user/Desktop/Lending Club/Short Datasets/accepted_2007_to_2018Q4-3.csv')

In [20]:
ds1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
ds1.shape

(660701, 151)

In [31]:
pd.set_option('display.max_columns', None)
print(ds1.head())

         id  loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  \
0  68407277     3600.0       3600.0           3600.0   36 months     13.99
1  68355089    24700.0      24700.0          24700.0   36 months     11.99
2  68341763    20000.0      20000.0          20000.0   60 months     10.78
3  66310712    35000.0      35000.0          35000.0   60 months     14.85
4  68476807    10400.0      10400.0          10400.0   60 months     22.45

   installment grade sub_grade                    emp_title emp_length  \
0       123.03     C        C4                      leadman  10+ years
1       820.28     C        C1                     Engineer  10+ years
2       432.66     B        B4                 truck driver  10+ years
3       829.90     C        C5  Information Systems Officer  10+ years
4       289.91     F        F1          Contract Specialist    3 years

  home_ownership  annual_inc verification_status   issue_d loan_status  \
0       MORTGAGE     55000.0        Not Verified  Dec-2015  Fully Paid
1       MORTGAGE     65000.0        Not Verified  Dec-2015  Fully Paid
2       MORTGAGE     63000.0        Not Verified  Dec-2015  Fully Paid
3       MORTGAGE    110000.0     Source Verified  Dec-2015     Current
4       MORTGAGE    104433.0     Source Verified  Dec-2015  Fully Paid

  pymnt_plan                                                url  \
0          n  https://lendingclub.com/browse/loanDetail.acti...
1          n  https://lendingclub.com/browse/loanDetail.acti...
2          n  https://lendingclub.com/browse/loanDetail.acti...
3          n  https://lendingclub.com/browse/loanDetail.acti...
4          n  https://lendingclub.com/browse/loanDetail.acti...

              purpose               title zip_code addr_state    dti  \
0  debt_consolidation  Debt consolidation    190xx         PA   5.91
1      small_business            Business    577xx         SD  16.06
2    home_improvement                 NaN    605xx         IL  10.78
3  debt_consolidation  Debt consolidation    076xx         NJ  17.06
4      major_purchase      Major purchase    174xx         PA  25.37

   delinq_2yrs earliest_cr_line  fico_range_low  fico_range_high  \
0          0.0         Aug-2003           675.0            679.0
1          1.0         Dec-1999           715.0            719.0
2          0.0         Aug-2000           695.0            699.0
3          0.0         Sep-2008           785.0            789.0
4          1.0         Jun-1998           695.0            699.0

   inq_last_6mths  mths_since_last_delinq  open_acc  pub_rec  revol_bal  \
0             1.0                    30.0       7.0      0.0     2765.0
1             4.0                     6.0      22.0      0.0    21470.0
2             0.0                     NaN       6.0      0.0     7869.0
3             0.0                     NaN      13.0      0.0     7802.0
4             3.0                    12.0      12.0      0.0    21929.0

   revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv  \
0        29.7       13.0                   w       0.00           0.00
1        19.2       38.0                   w       0.00           0.00
2        56.2       18.0                   w       0.00           0.00
3        11.6       17.0                   w   15897.65       15897.65
4        64.5       35.0                   w       0.00           0.00

    total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  \
0   4421.723917          4421.72          3600.00         821.72
1  25679.660000         25679.66         24700.00         979.66
2  22705.924294         22705.92         20000.00        2705.92
3  31464.010000         31464.01         19102.35       12361.66
4  11740.500000         11740.50         10400.00        1340.50

   total_rec_late_fee  recoveries  collection_recovery_fee last_pymnt_d  \
0                 0.0         0.0                      0.0     Jan-2019
1                 0.0         0.0                      0.0     Jun-2016
2                 0.0         0.0                      0.0     Jun-2017
3                 0.0         0.0                      0.0     Feb-2019
4                 0.0         0.0                      0.0     Jul-2016

   last_pymnt_amnt last_credit_pull_d  last_fico_range_high  \
0           122.67           Mar-2019                 564.0
1           926.35           Mar-2019                 699.0
2         15813.30           Mar-2019                 704.0
3           829.90           Mar-2019                 679.0
4         10128.96           Mar-2018                 704.0

   last_fico_range_low  collections_12_mths_ex_med  policy_code  \
0                560.0                         0.0          1.0
1                695.0                         0.0          1.0
2                700.0                         0.0          1.0
3                675.0                         0.0          1.0
4                700.0                         0.0          1.0

  application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  open_acc_6m  \
0       Individual             0.0         722.0     144904.0          2.0
1       Individual             0.0           0.0     204396.0          1.0
2        Joint App             0.0           0.0     189699.0          0.0
3       Individual             0.0           0.0     301500.0          1.0
4       Individual             0.0           0.0     331730.0          1.0

   open_act_il  open_il_12m  open_il_24m  total_bal_il  open_rv_12m  \
0          2.0          0.0          1.0        4981.0          3.0
1          1.0          0.0          1.0       18005.0          2.0
2          1.0          0.0          4.0       10827.0          0.0
3          1.0          0.0          1.0       12609.0          1.0
4          3.0          0.0          3.0       73839.0          4.0

   open_rv_24m  max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl
0          3.0       722.0      34.0            9300.0     3.0          1.0
1          3.0      6472.0      29.0          111800.0     0.0          0.0
2          2.0      2081.0      65.0           14000.0     2.0          5.0
3          1.0      6987.0      45.0           67300.0     0.0          1.0
4          7.0      9702.0      78.0           34000.0     2.0          1.0

In [21]:
pd.set_option('display.max_rows', None)
# Calculate the total number of rows
total_rows = len(ds1)

# Calculate the count of null values in each column
null_counts = ds1.isnull().sum()

# Calculate the percentage of null values in each column
null_percentage = (null_counts / total_rows) * 100

# Create a DataFrame to display the results
null_df = pd.DataFrame({'Column Name': null_counts.index, 'Null Count': null_counts.values, 'Null Percentage': null_percentage.values})

# Print the DataFrame with null counts and percentages
print(null_df)

                                    Column Name  Null Count  Null Percentage
0                                            id           0         0.000000
1                                     member_id      660701       100.000000
2                                     loan_amnt          15         0.002270
3                                   funded_amnt          15         0.002270
4                               funded_amnt_inv          15         0.002270
5                                          term          15         0.002270
6                                      int_rate          15         0.002270
7                                   installment          15         0.002270
8                                         grade          15         0.002270
9                                     sub_grade          15         0.002270
10                                    emp_title       45102         6.826386
11                                   emp_length       39243         5.939601
12                               home_ownership          15         0.002270
13                                   annual_inc          19         0.002876
14                          verification_status          15         0.002270
15                                      issue_d          15         0.002270
16                                  loan_status          15         0.002270
17                                   pymnt_plan          15         0.002270
18                                          url          15         0.002270
19                                         desc      549976        83.241285
20                                      purpose          15         0.002270
21                                        title        5467         0.827454
22                                     zip_code          16         0.002422
23                                   addr_state          15         0.002270
24                                          dti         342         0.051763
25                                  delinq_2yrs          44         0.006660
26                             earliest_cr_line          44         0.006660
27                               fico_range_low          15         0.002270
28                              fico_range_high          15         0.002270
29                               inq_last_6mths          44         0.006660
30                       mths_since_last_delinq      345891        52.352123
31                       mths_since_last_record      560067        84.768602
32                                     open_acc          44         0.006660
33                                      pub_rec          44         0.006660
34                                    revol_bal          15         0.002270
35                                   revol_util         632         0.095656
36                                    total_acc          44         0.006660
37                          initial_list_status          15         0.002270
38                                    out_prncp          15         0.002270
39                                out_prncp_inv          15         0.002270
40                                  total_pymnt          15         0.002270
41                              total_pymnt_inv          15         0.002270
42                              total_rec_prncp          15         0.002270
43                                total_rec_int          15         0.002270
44                           total_rec_late_fee          15         0.002270
45                                   recoveries          15         0.002270
46                      collection_recovery_fee          15         0.002270
47                                 last_pymnt_d         800         0.121084
48                              last_pymnt_amnt          15         0.002270
49                                 next_pymnt_d      429140        64.952225
50                           last_credit_pull_d          44         0.006660
51                         last_fico_range_high          15         0.002270
52                          last_fico_range_low          15         0.002270
53                   collections_12_mths_ex_med         160         0.024217
54                  mths_since_last_major_derog      509294        77.083885
55                                  policy_code          15         0.002270
56                             application_type          15         0.002270
57                             annual_inc_joint      632708        95.763136
58                                    dti_joint      632708        95.763136
59                    verification_status_joint      632757        95.770553
60                               acc_now_delinq          44         0.006660
61                                 tot_coll_amt       70291        10.638852
62                                  tot_cur_bal       70291        10.638852
63                                  open_acc_6m      230731        34.922151
64                                  open_act_il      230731        34.922151
65                                  open_il_12m      230731        34.922151
66                                  open_il_24m      230731        34.922151
67                           mths_since_rcnt_il      243394        36.838752
68                                 total_bal_il      230731        34.922151
69                                      il_util      290422        43.956646
70                                  open_rv_12m      230731        34.922151
71                                  open_rv_24m      230731        34.922151
72                                   max_bal_bc      230731        34.922151
73                                     all_util      230789        34.930929
74                             total_rev_hi_lim       70291        10.638852
75                                       inq_fi      230731        34.922151
76                                  total_cu_tl      230731        34.922151
77                                 inq_last_12m      230731        34.922151
78                         acc_open_past_24mths       50045         7.574531
79                                  avg_cur_bal       70309        10.641576
80                               bc_open_to_buy       57058         8.635979
81                                      bc_util       57332         8.677450
82                     chargeoff_within_12_mths         160         0.024217
83                                  delinq_amnt          44         0.006660
84                           mo_sin_old_il_acct       89085        13.483406
85                         mo_sin_old_rev_tl_op       70292        10.639003
86                        mo_sin_rcnt_rev_tl_op       70292        10.639003
87                               mo_sin_rcnt_tl       70291        10.638852
88                                     mort_acc       50045         7.574531
89                         mths_since_recent_bc       56569         8.561967
90                     mths_since_recent_bc_dlq      520775        78.821585
91                        mths_since_recent_inq      119576        18.098353
92               mths_since_recent_revol_delinq      458481        69.393114
93                        num_accts_ever_120_pd       70291        10.638852
94                               num_actv_bc_tl       70291        10.638852
95                              num_actv_rev_tl       70291        10.638852
96                                  num_bc_sats       58605         8.870124
97                                    num_bc_tl       70291        10.638852
98                                    num_il_tl       70291        10.638852
99                                num_op_rev_tl       70291        10.638852
100                               num_rev_accts       70291        10.638852
101                         num_rev_tl_bal_gt_0       70291        10.638852
102                                    num_sats       58605         8.870124
103                            num_tl_120dpd_2m       91404        13.834397
104                                num_tl_30dpd       70291        10.638852
105                          num_tl_90g_dpd_24m       70291        10.638852
106                          num_tl_op_past_12m       70291        10.638852
107                              pct_tl_nvr_dlq       70444        10.662009
108                            percent_bc_gt_75       57079         8.639158
109                        pub_rec_bankruptcies        1380         0.208869
110                                   tax_liens         120         0.018163
111                             tot_hi_cred_lim       70291        10.638852
112                           total_bal_ex_mort       50045         7.574531
113                              total_bc_limit       50045         7.574531
114                  total_il_high_credit_limit       70291        10.638852
115                             revol_bal_joint      640744        96.979420
116                      sec_app_fico_range_low      640743        96.979269
117                     sec_app_fico_range_high      640743        96.979269
118                    sec_app_earliest_cr_line      640743        96.979269
119                      sec_app_inq_last_6mths      640743        96.979269
120                            sec_app_mort_acc      640743        96.979269
121                            sec_app_open_acc      640743        96.979269
122                          sec_app_revol_util      641131        97.037994
123                         sec_app_open_act_il      640743        96.979269
124                       sec_app_num_rev_accts      640743        96.979269
125            sec_app_chargeoff_within_12_mths      640743        96.979269
126          sec_app_collections_12_mths_ex_med      640743        96.979269
127         sec_app_mths_since_last_major_derog      653742        98.946725
128                               hardship_flag          15         0.002270
129                               hardship_type      657102        99.455276
130                             hardship_reason      657102        99.455276
131                             hardship_status      657102        99.455276
132                               deferral_term      657102        99.455276
133                             hardship_amount      657102        99.455276
134                         hardship_start_date      657102        99.455276
135                           hardship_end_date      657102        99.455276
136                     payment_plan_start_date      657102        99.455276
137                             hardship_length      657102        99.455276
138                                hardship_dpd      657102        99.455276
139                        hardship_loan_status      657102        99.455276
140  orig_projected_additional_accrued_interest      657886        99.573937
141              hardship_payoff_balance_amount      657102        99.455276
142                hardship_last_payment_amount      657102        99.455276
143                         disbursement_method          15         0.002270
144                        debt_settlement_flag          15         0.002270
145                   debt_settlement_flag_date      651551        98.615107
146                           settlement_status      651551        98.615107
147                             settlement_date      651551        98.615107
148                           settlement_amount      651551        98.615107
149                       settlement_percentage      651551        98.615107
150                             settlement_term      651551        98.615107

In [22]:
ds1 = ds1.iloc[:, :-36]

In [23]:
# List of column names to delete
columns_to_delete = ['member_id', 'desc', 'mths_since_last_record', 'next_pymnt_d', 'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'mths_since_rcnt_il', 'il_util', 'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'url']

# Delete the specified columns
ds1.drop(columns=columns_to_delete, inplace=True)

In [24]:
# Count of different values in the column
value_counts = ds1['loan_status'].value_counts()

# Total count of values in the column
total_count = len(ds1['loan_status'])

# Print the count and different values
print("Total Count:", total_count)
print("\nCount of Different Values:")
print(value_counts)

Total Count: 660701

Count of Different Values:
loan_status
Fully Paid                                             345860
Current                                                218399
Charged Off                                             83265
Late (31-120 days)                                       6655
In Grace Period                                          2415
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1327
Does not meet the credit policy. Status:Charged Off       761
Default                                                    16
Name: count, dtype: int64

In [25]:
# List of specified words you want to replace with 0
specified_words = ['Charged Off', 'Late (31-120 days)', 'Default']

# Replace specified words with 0 in the specified column
ds1['loan_status'] = ds1['loan_status'].replace(specified_words, 0)

Turning Bad Loans into 0

In [26]:
# Count of different values in the column
value_counts = ds1['loan_status'].value_counts()

# Total count of values in the column
total_count = len(ds1['loan_status'])

# Print the count and different values
print("Total Count:", total_count)
print("\nCount of Different Values:")
print(value_counts)

Total Count: 660701

Count of Different Values:
loan_status
Fully Paid                                             345860
Current                                                218399
0                                                       89936
In Grace Period                                          2415
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1327
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

Turning Good Loans into 1

In [27]:
# List of specified words you want to replace with 0
specified_words = ['Fully Paid']

# Replace specified words with 0 in the specified column
ds1['loan_status'] = ds1['loan_status'].replace(specified_words, 1)

Deleting all the rows containing Current, In Grace Period, Late(16-30 days)

In [28]:
# Specify the entry you want to remove rows containing
entry_to_remove = 'Current'

# Filter the DataFrame to exclude rows containing the specified entry
ds1 = ds1[ds1['loan_status'] != entry_to_remove]

In [61]:
# Specify the entry you want to remove rows containing
entry_to_remove = 'In Grace Period'

# Filter the DataFrame to exclude rows containing the specified entry
ds1 = ds1[ds1['loan_status'] != entry_to_remove]

In [62]:
# Specify the entry you want to remove rows containing
entry_to_remove = 'Late (16-30 days)'

# Filter the DataFrame to exclude rows containing the specified entry
ds1 = ds1[ds1['loan_status'] != entry_to_remove]

In [63]:
# Specify the entry you want to remove rows containing
entry_to_remove = 'Does not meet the credit policy. Status:Fully Paid'

# Filter the DataFrame to exclude rows containing the specified entry
ds1 = ds1[ds1['loan_status'] != entry_to_remove]

In [64]:
# Specify the entry you want to remove rows containing
entry_to_remove = 'Does not meet the credit policy. Status:Charged Off'

# Filter the DataFrame to exclude rows containing the specified entry
ds1 = ds1[ds1['loan_status'] != entry_to_remove]

In [65]:
ds1 = ds1.drop(ds1[ds1['loan_status'] == 'Late (16-30 days)'].index)

In [66]:
ds1 = ds1.drop(ds1[ds1['loan_status'] == 'Does not meet the credit policy. Status:Fully Paid'].index)

In [67]:
ds1 = ds1.drop(ds1[ds1['loan_status'] == 'Does not meet the credit policy. Status:Charged Off'].index)

In [69]:
# Count of different values in the column
value_counts = ds1['loan_status'].value_counts()

# Total count of values in the column
total_count = len(ds1['loan_status'])

# Print the count and different values
print("Total Count:", total_count)
print("\nCount of Different Values:")
print(value_counts)

Total Count: 435811

Count of Different Values:
loan_status
1    345860
0     89936
Name: count, dtype: int64

Now we have ds_1 containing only 1 and 0 (good and bad loans values)

We should now select all the bad loans and almost equal number of good loans and then make a new csv file containing this data

In [71]:
ds1 = ds1.sort_values(by="loan_status")

In [72]:
ds1.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
5,131344335,18000.0,18000.0,18000.0,36 months,17.47,645.97,D,D1,Driver,...,0.0,4.0,92.6,66.7,0.0,0.0,92830.0,59107.0,12800.0,61930.0
7,130494879,8000.0,8000.0,7975.0,36 months,13.58,271.80,C,C2,Applications Analyst,...,0.0,3.0,97.7,20.0,0.0,0.0,247294.0,31506.0,24800.0,38219.0
8,131339159,35000.0,35000.0,35000.0,36 months,9.43,1120.01,B,B1,Enterprise Sales,...,0.0,6.0,95.5,0.0,0.0,0.0,510862.0,94379.0,13000.0,84151.0
9,131352740,15000.0,15000.0,15000.0,36 months,7.34,465.50,A,A4,Director of Clinical Services,...,0.0,1.0,100.0,33.3,0.0,0.0,50900.0,24800.0,47200.0,0.0
10,131257943,20000.0,20000.0,20000.0,60 months,11.98,444.69,B,B5,Territory Manager,...,0.0,7.0,100.0,0.0,1.0,0.0,473065.0,87138.0,51600.0,64962.0

We can see that Bad Loans are placed before Good Loans in the sorted dataset so if we select almost double the Bad Data rows and make a new table using that then we will have almost an equal number of Good Loand and Bad Loans cases with us

In [73]:
final_ds1 = ds1.iloc[:200000]

Exporting the final_ds1 dataset as a csv file

In [74]:
final_ds1.to_csv('final_dataset_3.csv', index=False)

We have achieved our target of cleaning the data and finding almost equal number of good and bad loans using this code

Our output is saved as 3 csv files which have to be compiled into 1, forming the final dataset